package com.cmcdelhi.quasar.paymentDetails;

public enum PaymentStatus {
	FULLPAID, REGISTRATIONPAID, UNPAID, PAID, FIRSTPAID, SECONDPAID, THIRDPAID, FOURTHPAID, FIFTHPAID, SIXTHPAID, SEVENTHPAID, EIGHTHPAID, NINTHPAID, TENTHPAID;
}
